"""add source_message_id to transfer

Revision ID: 8cdb72ea0896
Revises: b1e974299cb3
Create Date: 2026-08-31 21:43:12.070569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdb72ea0896'
down_revision: Union[str, Sequence[str], None] = 'b1e974299cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('source_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer', 'source_message_id')
    # ### end Alembic commands ###
