"""initial schema

Revision ID: b1e974299cb3
Revises: 
Create Date: 2026-08-31 00:18:32.862911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e974299cb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nextcloud_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_url', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'server_url')
    )
    op.create_index('idx_credential_user', 'nextcloud_credential', ['user_id'], unique=False)
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_file_id', sa.Text(), nullable=False),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('final_filename', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('upload_session_id', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("state IN ('queued','downloading','uploading','retrying','completed','failed','cancelled')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transfer_state', 'transfer', ['state'], unique=False)
    op.create_index('idx_transfer_user', 'transfer', ['user_id'], unique=False)
    op.create_table('chunk_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('upload_session_id', sa.Text(), nullable=False),
    sa.Column('chunk_number', sa.Integer(), nullable=False),
    sa.Column('chunk_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','uploaded','failed')"),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_session_id', 'chunk_number')
    )
    op.create_index('idx_chunk_transfer', 'chunk_record', ['transfer_id'], unique=False)
    op.create_table('transfer_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.Text(), nullable=True),
    sa.Column('to_state', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("to_state IN ('queued','downloading','uploading','retrying','completed','failed','cancelled')"),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_transfer', 'transfer_history', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_history_transfer', table_name='transfer_history')
    op.drop_table('transfer_history')
    op.drop_index('idx_chunk_transfer', table_name='chunk_record')
    op.drop_table('chunk_record')
    op.drop_index('idx_transfer_user', table_name='transfer')
    op.drop_index('idx_transfer_state', table_name='transfer')
    op.drop_table('transfer')
    op.drop_index('idx_credential_user', table_name='nextcloud_credential')
    op.drop_table('nextcloud_credential')
    # ### end Alembic commands ###
